[package]
name = "gnalose_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
derive-new = "0.5.9"
derive_more = "*"
enum_unwrapper = "0.1.2"
subenum = "1.0.1"

